// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechMoveGLMS.Data;

#nullable disable

namespace TechMoveGLMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518170436_AddDriverSystem")]
    partial class AddDriverSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TechMoveGLMS.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Trade Center, New York, NY 10001",
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2403),
                            Email = "contact@globalfreight.com",
                            Name = "Global Freight Solutions",
                            Phone = "+1-555-0101",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Marienstraße 15, Berlin 10117",
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2408),
                            Email = "info@eurologistics.de",
                            Name = "EuroLogistics GmbH",
                            Phone = "+49-30-1234567",
                            Region = "Europe"
                        });
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedAgreementFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedAgreementPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Full-service international shipping with priority handling",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = "Premium",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Annual Shipping Agreement 2026"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2686),
                            Description = "Time-sensitive cargo delivery across Europe",
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = "Express",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Express Cargo Services"
                        });
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LicenseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City",
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2825),
                            DateHired = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@techmove.com",
                            EmployeeNumber = "DRV001",
                            FullName = "John Smith",
                            LicenseExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "LIC123456",
                            LicenseType = 2,
                            Phone = "+1-555-0101",
                            Status = 0,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, City",
                            CreatedAt = new DateTime(2026, 5, 18, 17, 4, 34, 833, DateTimeKind.Utc).AddTicks(2833),
                            DateHired = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.johnson@techmove.com",
                            EmployeeNumber = "DRV002",
                            FullName = "Mike Johnson",
                            LicenseExpiryDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "LIC789012",
                            LicenseType = 1,
                            Phone = "+1-555-0102",
                            Status = 0,
                            YearsOfExperience = 5
                        });
                });

            modelBuilder.Entity("TechMoveGLMS.Models.DriverSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedDistanceKM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceRequestId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("DriverSchedules");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountZAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountZAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountUSD = 1500.00m,
                            AmountZAR = 29250.00m,
                            CompletedDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractId = 1,
                            Description = "Shipment of 20 containers from NY to London",
                            ExchangeRate = 19.50m,
                            RequestDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            Title = "Container Shipment - Q1 2026"
                        },
                        new
                        {
                            Id = 2,
                            AmountUSD = 875.50m,
                            AmountZAR = 17072.25m,
                            ContractId = 2,
                            Description = "Time-sensitive documents and small packages",
                            ExchangeRate = 19.50m,
                            RequestDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Express Air Freight"
                        });
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Contract", b =>
                {
                    b.HasOne("TechMoveGLMS.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.DriverSchedule", b =>
                {
                    b.HasOne("TechMoveGLMS.Models.Driver", "Driver")
                        .WithMany("Schedules")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechMoveGLMS.Models.ServiceRequest", "ServiceRequest")
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Invoice", b =>
                {
                    b.HasOne("TechMoveGLMS.Models.ServiceRequest", "ServiceRequest")
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.ServiceRequest", b =>
                {
                    b.HasOne("TechMoveGLMS.Models.Contract", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Contract", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("TechMoveGLMS.Models.Driver", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
